
# Conteneur Nginx pour le front
FROM nginx:alpine

# Copie frontend existant dans Nginx
COPY ./frontend/public /usr/share/nginx/html

# Copie la config Nginx (avec try_files pour router JS)
COPY ./config/nginx/default.conf /etc/nginx/conf.d/default.conf

# Exposer le port 80
EXPOSE 80

# Lance Nginx
CMD ["nginx", "-g", "daemon off;"]
