
# Conteneur Nginx léger pour servir le front
FROM nginx:alpine

# Copier ton frontend existant dans Nginx
COPY ./frontend/public /usr/share/nginx/html

# Copier la config Nginx (avec try_files pour router JS)
COPY ./config/nginx/default.conf /etc/nginx/conf.d/default.conf

# Exposer le port 80
EXPOSE 80

# Lancer Nginx
CMD ["nginx", "-g", "daemon off;"]
